//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından otomatik olarak üretildi.
//     Dosyada manuel değişiklik yapmayınız; değişiklikler üzerine yazılır.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_Kontrol_V2.Properties
{
    /// <summary>
    /// Uygulama ayarlarına (Settings) kolay erişim sağlayan, otomatik oluşturulmuş sınıf.
    /// </summary>
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(
        "Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static readonly Settings defaultInstance =
            (Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings()));

        /// <summary>
        /// Uygulama ayarlarının varsayılan, thread-safe örneği.
        /// </summary>
        public static Settings Default => defaultInstance;

        // Buraya property'ler eklenebilir. Örneğin:
        // [global::System.Configuration.UserScopedSetting()]
        // [global::System.Diagnostics.DebuggerNonUserCode()]
        // [global::System.Configuration.DefaultSettingValue("VarsayılanDeğer")]
        // public string AyarAdi {
        //     get { return ((string)(this["AyarAdi"])); }
        //     set { this["AyarAdi"] = value; }
        // }
    }
}
